version: '3'
services:
  app:
    build: .
    tty: true
    stdin_open: true
    command: /bin/bash -c "bundle exec ruby app.rb -o 0.0.0.0"
    volumes:
      - .:/src
    ports:
      - "4567:4567"
