name: Ruby

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'doc/images/**'
      - '**.md'

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      shell: bash
      run:  |
        docker-compose run --rm app bundle exec rspec
      env:
        RACK_ENV: test
